version: '3'
services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: iclock
    ports:
      - 8888:8080
    restart: always
    volumes:
        - ./logfile.txt:/usr/local/tomcat/webapps/iclock/WEB-INF/logfile.txt
  
