version: '3'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'epushdata'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpassword'
      MYSQL_ROOT_PASSWORD: 'rootPassword'
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - ./dbbackup:/dbbackup
      - ./db:/var/lib/mysql 
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: iclock
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  